name: Cargonaut
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Derive appropriate SHAs for base and head for `nx affected` commands
              uses: nrwl/nx-set-shas@v2
            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - name: Cache
              uses: actions/cache@v2
              with:
                  path: |
                      ~/dist
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm i
            - name: Format
              run: npm run format:check
            - name: Lint
              run: npm run ci:lint
            - name: Documentation
              run: npm run ci:doc
            - name: Build
              run: npm run ci:build
            - name: Test
              run: npm run ci:test
            - name: E2E
              run: npm run ci:e2e
            - name: Firebase deployment
              if: ${{ (github.ref == 'refs/heads/main')}}
              run: npm i -g firebase-tools && firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
