name: Test Cargonaut
on:
    pull_request:
        branches: [main]
        types: [opened, synchronize]
jobs:
    workflow:
        name: Cargonaut CI/CD
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        strategy:
            matrix:
                node-version: [12.x, 14.x, 16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Format
              run: npm run format:check
            - name: Lint
              run: npm run all:lint
            - name: Documentation
              run: npm run all:doc
            - name: Build
              run: npm run all:build
            - name: Test
              run: npm run all:test
            - name: E2E
              run: npm run all:e2e
