name: Deploy Cargonaut
on:
    pull_request:
        branches: [main]
        types: [ closed ]
jobs:
    workflow:
        name: Cargonaut CI/CD
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Firebase Deployment
              if: ${{ github.event.pull_request.merged }}
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARGONAUT }}'
                projectId: cargonaut
