name: Deploy Cargonaut
on:
    push:
        branches: [main]
jobs:
    deploy:
        name: Deployment
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@master
          - name: Download Artifact
            uses: actions/download-artifact@v1
            with:
              name: dist
          - uses: actions/checkout@v2
          - name: Use Node.js
            uses: actions/setup-node@v2
            with:
                node-version: 14.x
                cache: 'npm'
          - name: Firebase Deployment
            if: ${{ github.event.pull_request.merged }}
            run: npm i -g firebase-tools && \
                firebase deploy --token '${{ secrets.FIREBASE_TOKEN }}'
