name: Deploy Cargonaut
on:
    pull_request:
        branches: [main]
        types: [closed]
jobs:
    workflow:
        name: Cargonaut CI/CD
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Firebase Deployment
              if: ${{ github.event.pull_request.merged }}
              run: npm i -g firebase-tools && \
                   firebase deploy --token '${{ secrets.FIREBASE_TOKEN }}'
